### ISSUE TITLE
&shy (soft-hyphen) rendering in translation

### ISSUE THREAD

**Issue by bnjroos** [plentymarkets/plugin-ceres#193]
Hi there,

I am generating url using the following code:

> <div class="col-lg-3 col-sm-12 botlinks">
> <a href="/privacy-policy">{{ trans("Ceres::Template.generalPrivacyPolicy") }}</a>
> </div>

It generates &shy, how to get rid of that ? I have found no workaround even trying to replace it using javascript.

> Widerrufs&shy;recht
> Daten&shy;schutz&shy;erklärung

Thank you in advance,

Edit: we cannot see the "&shy" on github....

![opera_2017-11-07_09-48-41](https://user-images.githubusercontent.com/12064956/32474780-de5af9d4-c3a0-11e7-9328-b1994664da86.png)

**Comment by Sebsta13** [comment]
Hi,

the "&shy" is hardcoded in our translation for generalPrivacyPolicy. 

The reason for this is simply to help the browser know where to set the line break if needed.

But it is a html entity and I think you can't but this in your url without rendering the &shy, because for the url this is a normal string. 

The solution would be replacing it with js. Maybe you should check what you did? Could you send me the code?

Best regards,
Sebastian

**Comment by bnjroos** [comment]
Simple jquery replace with no luck:
```
$('#rm1').html().replace(/\&shy;/g, '');
$('#rm2').html().replace(/\&shy;/g, '');
```
any suggestion ?

**Comment by bnjroos** [comment]
With Ceres version 2.0, it seem to work now.
